class_name AlternityRulesConstants
extends RefCounted

const ABILITIES := ["STR", "DEX", "CON", "INT", "WIL", "PER"]
const MAX_SPECIALTY_RANK := 12
const ABILITY_NAMES := {
	"STR": "Strength",
	"DEX": "Dexterity",
	"CON": "Constitution",
	"INT": "Intelligence",
	"WIL": "Will",
	"PER": "Personality",
}

const OPTIONAL_RULES := [
	{
		"id": "2a",
		"name": "Optional Rule 2A",
		"summary": "Alternate starting skill points",
		"description": "New characters have skill points equal to 30 plus 3 times their INT score. Human heroes receive 5 additional skill points at character creation.",
	},
	{
		"id": "2b",
		"name": "Optional Rule 2B",
		"summary": "Alternate broad skill limit",
		"description": "During initial skill purchase, a character may not learn more than six additional broad skills, not counting racial broad skills. Modify this number by the hero's INT resistance modifier.",
	},
	{
		"id": "2c",
		"name": "Optional Rule 2C",
		"summary": "Flat specialty advancement cost",
		"description": "The cost to purchase rank 2 or higher in a specialty skill is either the list price or list price -1. Current ranks do not increase the cost of advancing that skill.",
	},
]

const COMPLEX_CHECK_RULES := {
	"summary": "Complex skill checks are used for tasks that take more than one roll or where the GM wants tension over time.",
	"successes": "Ordinary success counts as 1 success, Good as 2, and Amazing as 3.",
	"failures": "A Failure adds no progress. Three Failures ruin the attempt until conditions change; one Critical Failure can ruin it immediately.",
	"complexity": "Typical complexity: Marginal 2 successes, Ordinary 3-4, Good 5-7, Amazing 8-10. The GM chooses the exact target.",
}
const MUTATION_ADVANTAGE_TIERS := ["Ordinary", "Good", "Amazing"]
const MUTATION_DRAWBACK_TIERS := ["Slight", "Moderate", "Extreme"]
const MUTATION_ADVANTAGE_LABEL_ORDER := ["Amazing", "Good", "Ordinary"]
const MUTATION_DRAWBACK_LABEL_ORDER := ["Extreme", "Moderate", "Slight"]
const CORE_SKILL_ROLL_SOURCE := "Source: Player's Handbook p. 61-63."
const COMPLEX_CHECK_SOURCE := "Source: Player's Handbook p. 62."

const SPECIES_FREE_SPECIALTY_IDS := {
	3: [24],
}

const MISSING_SKILL_LABELS := {
	525: "Telepathy",
}

const SPECIES_RULE_NOTES := {
	0: [
		"Skill Bonus: Humans begin with 5 more skill points than other species and may start with one more broad skill. Applied to skill budget and broad-skill limit. Source: Player's Handbook p. 30; Table P5 p. 34.",
	],
	1: [
		"Psionic Powers: Fraal use the optional psionics rules when fraal are present in a campaign. Source: Player's Handbook p. 21-22.",
		"Psionic Energy: Fraal talents or Diplomats with Mindwalker as secondary profession use WIL for psionic energy points instead of one-half WIL. Source: Player's Handbook p. 22.",
		"Mindwalkers: Fraal Mindwalkers use WIL x 1.5 for psionic energy points instead of WIL x 1. Source: Player's Handbook p. 22.",
		"Telepathy: Telepathy is one of every fraal hero's free broad skills. Source: Player's Handbook p. 22; Table P4 p. 34.",
	],
	2: [
		"Computer Operation Skill Bonus: Mechalus receive a -1 step bonus when using Knowledge-computer operation or Computer Science-hacking while merged with a computer; merging or disengaging takes one round. Applied to those skill dice. Source: Player's Handbook p. 24.",
		"Cybernetic Enhancements: Mechalus begin with two neural data slots, an internal processor equivalent to a Good nanocomputer, and bio-organic circuitry similar to a reflex device. Source: Player's Handbook p. 24.",
		"Cybergear Tolerance: Mechalus are not subject to cybernetic rejection, and their cybergear limit is CON +4 instead of CON. Source: Player's Handbook p. 24.",
	],
	3: [
		"Flight: Sesheyans can fly in atmospheres at least half Earth pressure and gravity no higher than Earth-normal. Applied to glide and fly movement rates. Source: Player's Handbook p. 26.",
		"Flight Checks: Sesheyans use the Acrobatics broad skill for flying checks and may buy the flight specialty. Source: Player's Handbook p. 26.",
		"Zero-G Training: Sesheyans function as if they have Acrobatics-zero-g training rank 1. Applied as a free specialty rank. Source: Player's Handbook p. 26.",
		"Falling: A conscious sesheyan able to use wings suffers no impact damage from a fall and glides safely; otherwise normal impact damage applies. Source: Player's Handbook p. 26; impact damage p. 58.",
		"Night Vision: Sesheyans ignore low-illumination penalties except in total darkness, unless wearing protective goggles against light sensitivity. Source: Player's Handbook p. 26.",
		"Light Sensitivity: Ordinary, Good, and Amazing illumination impose +1, +2, and +3 step penalties; protective goggles negate this. Source: Player's Handbook p. 26.",
	],
	4: [
		"Action Check Bonus: T'sa receive a -1 step situation die bonus to action checks. Applied to action check die. Source: Player's Handbook p. 27.",
		"Juryrig Bonus: T'sa receive a -1 step situation die bonus on Technical Science-juryrig checks. Applied to the juryrig skill die. Source: Player's Handbook p. 27.",
		"Body Armor: T'sa natural armor is d4+1 low impact, d4 high impact, and d4-1 energy. Source: Player's Handbook p. 27.",
	],
	5: [
		"Superior Durability: Weren durability scores use CON x 1.5, rounded down. Applied to durability. Source: Player's Handbook p. 28.",
		"Natural Weapon: On a successful Unarmed Attack-brawl or power martial arts check, weren claws deal d4w/d4+2w/d4m low-impact damage plus Strength bonuses. Source: Player's Handbook p. 28.",
		"Camouflage: In natural terrain, ranged weapon attacks aimed at a weren suffer a +1 step penalty. Source: Player's Handbook p. 28.",
		"Primitive Culture: Weren suffer a +2 step penalty when using PL4 or higher items; this can be reduced by paying 4 skill points, then removed at 6th level or higher by paying 4 more. Source: Player's Handbook p. 28-29.",
	],
	6: [
		"Mutants use the Chapter 13 mutation rules. Mutant heroes are derived from human stock, have the human free broad skills, do not receive the human skill point or broad skill bonus, and must have at least one advantageous mutation and one drawback. Source: Player's Handbook p. 213-214.",
	],
}

const SPECIES_ROLL_NOTES := {
	2: [
		"Mechalus: Knowledge-computer operation and Computer Science-hacking receive a -1 step bonus while merged with a computer. Source: Player's Handbook p. 24.",
	],
	3: [
		"Sesheyan: Acrobatics-zero-g training is treated as rank 1 before purchased ranks. Source: Player's Handbook p. 26.",
		"Sesheyan: Light sensitivity imposes +1/+2/+3 step penalties in Ordinary/Good/Amazing illumination unless protective goggles are worn. Source: Player's Handbook p. 26.",
	],
	4: [
		"T'sa: Action checks use a -d4 base situation die from the racial action check bonus. Source: Player's Handbook p. 27.",
		"T'sa: Technical Science-juryrig receives a -1 step situation die bonus. Source: Player's Handbook p. 27.",
	],
	5: [
		"Weren: Ranged weapon attacks against a weren in natural terrain suffer a +1 step penalty. Source: Player's Handbook p. 28.",
		"Weren: PL4 or higher item use suffers a +2 step penalty until the primitive culture penalty is bought down. Source: Player's Handbook p. 28-29.",
		"Weren: Claw attacks after successful Unarmed Attack-brawl or power martial arts checks deal d4w/d4+2w/d4m low-impact damage plus Strength bonuses. Source: Player's Handbook p. 28.",
	],
}

const MOVEMENT_EFFECTS := [
	{"mode": "Walk", "effect": "No penalty when moving and acting in the same phase."},
	{"mode": "Run", "effect": "+2 step penalty to another action in the same phase."},
	{"mode": "Sprint", "effect": "+3 step penalty to another action in the same phase."},
	{"mode": "Easy Swim", "effect": "+2 step penalty to another action in the same phase."},
	{"mode": "Swim", "effect": "No other actions in the same phase."},
	{"mode": "Glide", "effect": "+1 step penalty to another action in the same phase."},
	{"mode": "Fly", "effect": "+2 step penalty to another action in the same phase."},
	{"mode": "All-out", "effect": "Movement only; after stopping, no other action for the rest of the round."},
]

const MOVEMENT_RUN_BY_TOTAL := {
	6: 4,
	8: 6,
	10: 6,
	12: 8,
	14: 10,
	16: 10,
	18: 12,
	20: 12,
	22: 14,
	24: 16,
	26: 16,
	28: 18,
	30: 20,
	32: 20,
}

const BROAD_SKILL_SUMMARIES := {
	0: "Operate armor effectively and reduce armor-related action check and Dexterity resistance penalties.",
	3: "Handle athletic feats of strength such as climbing, jumping, and throwing.",
	8: "Use heavy personal and crew-served weapons, including direct-fire and indirect-fire weapons.",
	11: "Fight with hand weapons and use melee defenses such as parrying when appropriate.",
	15: "Fight without weapons, brawl, use martial arts, and attempt overpowering holds.",
	18: "Perform agile movement, stunts, dodges, controlled falls, and zero-g or flight maneuvers.",
	26: "Perform fine manual actions such as opening locks, picking pockets, and sleight of hand.",
	30: "Use modern firearms such as pistols, rifles, and submachine guns.",
	34: "Use older ranged weapons such as bows, crossbows, flintlocks, and slings.",
	39: "Avoid notice through hiding, shadowing, and silent movement.",
	43: "Operate common vehicles and specialized vehicle classes.",
	48: "Handle long-distance or demanding movement such as racing, swimming, and trailblazing.",
	52: "Endure fatigue, pain, harsh activity, and injury-related checks.",
	55: "Survive hostile environments by finding necessities and avoiding environmental danger.",
	57: "Understand commercial organizations, trade, and legal or illegal business practices.",
	61: "Work with computer systems, hardware, hacking, and programming.",
	65: "Use, build, place, and disarm explosives.",
	69: "Apply general education, languages, deduction, basic computer operation, and first aid.",
	75: "Understand law, court procedure, law enforcement practice, and legal specialties.",
	79: "Apply biological sciences such as biology, botany, genetics, xenology, and zoology.",
	85: "Apply medical sciences, diagnosis, psychology, surgery, treatment, and xenomedicine.",
	92: "Navigate by surface, system, or drivespace methods.",
	96: "Apply astronomy, chemistry, physics, and planetology.",
	101: "Understand security procedures, devices, and protection protocols.",
	104: "Operate ship, station, or installation systems such as sensors, defenses, engines, and weapons.",
	110: "Apply battlefield and operational planning for infantry, vehicle, and space combat.",
	114: "Build, invent, juryrig, repair, and understand technical systems.",
	119: "Navigate organizations through bureaucracy and management.",
	122: "Ride, train, and work with animals.",
	125: "Notice danger, read intuition, and perceive hidden details.",
	128: "Produce creative work in a chosen field.",
	130: "Interrogate, search, and track as part of formal investigation.",
	134: "Resist mental and physical pressure.",
	137: "Understand street-level contacts, rumors, and criminal elements.",
	140: "Teach a specific field to another character.",
	142: "Understand cultures and manage diplomacy, etiquette, and first-contact situations.",
	146: "Mislead, bluff, bribe, and gamble.",
	150: "Perform as an actor, dancer, musician, singer, or similar entertainer.",
	155: "Negotiate, charm, interview, intimidate, seduce, taunt, and bargain.",
	162: "Lead others through command and inspiration.",
	900: "The following psionic broad skill and its specialty skills are connected to a character's Constitution score. The broad skill has a base situation die of +d4; each of the specialty skills has a base die of +d0. This skill can't be used untrained. This skill allows a character to harness the power of his mind to enhance his body's functions. With just the broad skill, a character can attempt to use any of the related specialty skills except those that can't be used untrained. The difficulty of such an action is reflected in the increased psionic energy cost and the higher base situation die for using just the broad skill.",
	901: "The following psionic broad skill and its specialty skills are connected to a character's Personality score. The broad skill has a base situation die of +d4; each of the specialty skills has a base die of +d0. This skill can't be used untrained. This skill allows a character to open his mind to the thoughts of others or send his own thoughts into the minds of others. With just the broad skill, a character can attempt to use any of the related specialty skills except those that can't be used untrained. The difficulty of such an action is reflected in the increased psionic energy cost and the higher base situation die for using just the broad skill.",
	902: "The following psionic broad skill and its specialty skills are connected to a character's Will score. The broad skill has a base situation die of +d4; each of the specialty skills has a base die of +d0. This skill can't be used untrained. This skill allows a hero to manipulate his physical environment with only the power of his mind. With just the broad skill, a character can attempt to use any of the related specialty skills except those that can't be used untrained. The difficulty of such an action is reflected in the increased psionic energy cost and the higher base situation die for using just the broad skill.",
	903: "The following psionic broad skill and its specialty skills are connected to a character's Intelligence score. The broad skill has a base situation die of +d4; each of the specialty skills has a base die of +d0. This skill can't be used untrained. This skill allows a character to experience his environment through an agency beyond the normal senses, using the power of his mind. With just the broad skill, a character can attempt to use any of the related specialty skills except those that can't be used untrained. The difficulty of such an action is reflected in the increased psionic energy cost and the higher base situation die for using just the broad skill."
}

const SPECIALTY_SUMMARIES := {
	1: "Specialized operation of standard combat armor, including reducing armor penalties and shield parries.",
	2: "Specialized operation of powered armor; this skill cannot be used untrained.",
	4: "Climb walls, mountains, lines, and similar obstacles.",
	5: "Jump horizontally or vertically; distance depends on the result of the skill check.",
	6: "Throw objects accurately or for distance.",
	9: "Fire direct-fire heavy weapons at visible targets.",
	10: "Use indirect-fire heavy weapons such as mortars or launchers against areas or concealed targets.",
	12: "Use knives, swords, axes, and similar bladed weapons.",
	13: "Use clubs, maces, staffs, and similar blunt weapons.",
	14: "Use powered melee weapons.",
	16: "Use unarmed street fighting, boxing, wrestling, and similar close combat.",
	17: "Use offensive martial arts focused on strikes and power; this skill cannot be used untrained.",
	19: "Perform dangerous activities such as parachuting, diving, surfing, and other high-risk stunts.",
	20: "Use defensive martial arts focused on redirection, throws, sweeps, holds, and blocks.",
	21: "Use tumbling, rolling, cover, and evasive movement as a combat defense.",
	22: "Reduce harm from falling through controlled movement and landing technique.",
	23: "Perform difficult maneuvers while flying or gliding.",
	24: "Function in zero-g or low-g environments; this skill cannot be used untrained.",
	27: "Open locks and defeat mechanical locking systems.",
	28: "Steal small objects from another character without being noticed.",
	29: "Perform sleight of hand, palming, and stage-magic style manipulation.",
	31: "Use pistols.",
	32: "Use rifles.",
	33: "Use submachine guns.",
	35: "Use bows.",
	36: "Use crossbows.",
	37: "Use flintlock firearms.",
	38: "Use slings.",
	40: "Remain unnoticed by using cover, quiet, and stillness.",
	41: "Follow a target without being noticed.",
	42: "Move silently and avoid observation while moving.",
	44: "Operate a chosen air vehicle class; this skill cannot be used untrained.",
	45: "Operate a chosen land vehicle class.",
	46: "Operate a chosen space vehicle class; this skill cannot be used untrained.",
	47: "Operate a chosen water vehicle class.",
	49: "Run faster and sustain competitive ground movement; this skill cannot be used untrained.",
	50: "Swim effectively; this skill cannot be used untrained.",
	51: "Plan and maintain overland movement through difficult routes.",
	53: "Resist fatigue and the worsening of mortal damage.",
	54: "Resist pain and keep functioning under injury; this skill cannot be used untrained.",
	56: "Survive in a chosen environment or terrain type.",
	62: "Break into, bypass, or exploit computer systems; this skill cannot be used untrained.",
	63: "Work with computer hardware.",
	64: "Write, modify, and understand software.",
	66: "Disarm explosive devices.",
	67: "Build explosive devices from available materials; this skill cannot be used untrained.",
	68: "Place explosives for intended effect.",
	70: "Use everyday computer systems; this skill cannot be used untrained.",
	71: "Reach conclusions from evidence and logic.",
	72: "Provide immediate medical aid; this skill cannot be used untrained.",
	73: "Speak, read, or understand a specific language; this skill cannot be used untrained.",
	74: "Know facts about a specific field.",
	89: "Perform surgery; this skill cannot be used untrained.",
	90: "Treat injuries and illness; this skill cannot be used untrained.",
	91: "Practice medicine on a specific nonhuman species; this skill cannot be used untrained.",
	93: "Plot drivespace courses; this skill cannot be used untrained.",
	94: "Navigate within a star system.",
	95: "Navigate on or near a planetary surface.",
	102: "Understand protective procedures and security protocols.",
	103: "Find, bypass, or operate security devices.",
	115: "Design or create new technical solutions.",
	116: "Make quick field repairs or improvised technical fixes.",
	117: "Repair damaged devices and systems.",
	118: "Know technical facts and principles.",
	124: "Train a chosen animal type.",
	126: "Sense motives, danger, or the direction of a situation.",
	127: "Notice hidden or subtle physical details.",
	131: "Question a subject under pressure.",
	132: "Search an area or object for hidden information.",
	133: "Follow tracks and signs of passage.",
	135: "Resist mental pressure, fear, or psychic strain.",
	136: "Resist physical pressure, exhaustion, and bodily stress.",
	145: "Handle first contact with an unfamiliar culture or species; this skill cannot be used untrained.",
	156: "Negotiate price, exchange, or terms.",
	157: "Win friendly reactions through personal appeal.",
	158: "Draw information from a subject through conversation.",
	159: "Pressure another character through threat or presence.",
	160: "Use attraction and social pressure to influence another character.",
	161: "Provoke or distract an opponent.",
	163: "Direct others in a structured chain of command.",
	164: "Encourage others and improve morale; this skill cannot be used untrained.",
	90001: "Extended duration. When employing this skill, a character generates a staff or club of bio-kinetic energy that extends from his hand and can be used as a melee weapon. The bioweapon requires the Melee Attack-bludgeon skill to be wielded effectively. The bioweapon has a damage rating of d4/d4+2/d6+2 (plus any adjustment for Strength, if applicable), depending on the result of each Melee Attack-bludgeon skill check. The initial skill check used to generate the weapon determines the type of damage the weapon does for as long as the current weapon is maintained: Ordinary, stun; Good, wound; Amazing, mortal.",
	90002: "Extended duration. Through the use of this skill, a character can regulate his metabolic processes. This allows him to survive longer without food and water, in extreme climates, and in other hostile conditions. He can also slow his bodily functions to a point where he can pretend to be dead, should he need to fool others in some situation. A check is made when a character enters a hostile environment or otherwise wants to employ this skill. In the case of a hostile environment, the result of a skill check determines the type of protection a character can simulate by manipulating his own body: Ordinary, vacuum mask; Good, jumpsuit; Amazing, soft e-suit. After the initial use of the skill, the level of protection can be maintained every hour thereafter at a cost of 1 psionic energy point.",
	90003: "This skill can't be used untrained. By concentrating, a character using this skill can heal himself of wound damage or disease. How much damage can be healed depends on the result of a skill check: Ordinary, 1 wound point; Good, 2 points; Amazing, 3 points. For disease, the following results apply: Ordinary, reduce the degree of illness by one grade; Good, reduce by two grades; Amazing, reduce by three grades. Psionic healing requires time. The results are immediate, but the body's reaction to the use of the skill lasts one hour. For this reason, the heal skill can't be attempted more than once per hour, even if the check result is a Failure. Healing Mortal Damage: At rank 6, a character becomes able to heal mortal damage. Skill check results change to: Ordinary, 2 wounds; Good, 3 wounds or 1 mortal; Amazing, 4 wounds or 2 mortals.",
	90004: "This skill can't be used untrained. By using this skill, a character can alter his features so as to disguise himself or to accomplish something he wouldn't be able to do in his normal form, such as squeeze into a small hole, reach higher than his height or arm length normally allows, or shift his body mass to slip loose of bonds. Morphing requires an entire round (4 phases) to complete, from the moment the alteration starts to when it is finished. The character can do nothing else while this process is taking place. The initial check determines how long the morphed form lasts: Ordinary, 1 round; Good, 2 rounds; Amazing, 3 rounds. Extendable at 1 psionic energy point per round. Volume can be expanded/compressed, but mass cannot change. Original characteristics are retained; no game statistics change except those directly related to the morphing (e.g. elongated fingers can grant a -1 bonus to Manipulation-pickpocket checks). Has no effect on clothing/possessions.",
	90005: "When using this skill, a character can offset fatigue or stun damage, or some of each, that he has suffered. The skill does nothing to alleviate psionic energy loss. A successful skill check provides the character with a certain number of \"rejuvenation points.\" It costs 2 of these points to restore 1 point of fatigue damage, and 1 of these points to restore 1 point of stun damage. On an Ordinary success, the character receives 2 \"rejuvenation points\"; on a Good success, 4 points; and on an Amazing success, 6 points. The character can use these points in any combination to restore stun points, fatigue points, or some of each. \"Rejuvenation points\" that can't be used immediately are lost. Psionic rejuvenation requires time. The results are immediate, but the body's reaction to the use of the skill lasts one hour. For this reason, the rejuvenate skill can't be attempted more than once per hour.",
	90006: "By laying hands upon another character and making a successful skill check, the hero alleviates that character's damage or disease by absorbing it into himself. The damage that can be absorbed is tied to the result of a skill check: Critical Failure, character suffers 1 wound; Failure, no effect; Ordinary, hero absorbs 1 wound; Good, hero absorbs 2 wounds; Amazing, hero absorbs 3 wounds or 1 mortal. An Ordinary result reduces the patient's illness by one grade, simultaneously infecting the hero with that one grade of disease; a Good result reduces the patient's disease by two grades, transferring the ailment into the hero; and an Amazing result transfers any illness from the patient into the hero. Once the hero absorbs the damage or disease, he must either use the heal specialty skill, heal naturally, or receive medical or psionic attention.",
	90101: "Extended duration. With this skill, a character can send and receive thoughts to and from another character, usually for the purpose of exchanging information. Modifiers may apply, depending on the range, familiarity, and willingness of the target mind to be contacted. The type of thoughts that can be exchanged depends on the result of a skill check: On an Ordinary success, simple concepts (brief questions and one-word answers) can be exchanged. On a Good success, moderate discussion (pass notes back and forth, one note per 2 phases) can occur. On an Amazing success, the communicating characters can have a detailed discussion, as though they were conversing vocally. If the target mind is unwilling to communicate, its Will resistance modifier is applied as a penalty. If contact is established anyway, the unwilling mind can expel the user by making a successful Will feat check or Resolve-mental resolve check with a +1/+2/+3 penalty.",
	90102: "Extended duration. This skill can't be used untrained. This skill is the ability to link one's mind with a computer or a cybernetic machine without using a physical connection of any kind. The datalink skill can be used to operate computers with mental commands, to project one's mind into the datastream, or to examine computer data by mentally scanning the storage unit. To initiate the link, the user must be within 6 meters of the point of entry (+1 penalty if >2m, +2 if >4m). A computer's normal defenses provide a penalty to the psionics-user's skill check. Otherwise, datalink can be used to accomplish any task that can be performed with the use of any computer.",
	90103: "Extended duration. This skill enables a character to fool a target's mind by projecting an illusion into it. An illusion can be a sight or a sound, but no other senses can be affected. An illusion is not capable of directly causing damage. The skill is usable only against targets the character can see, and it has a maximum range of 5 meters per skill rank of the user. Any actions the user attempts while maintaining an illusion receive a +1 penalty. The result of the character's skill check determines how powerful the illusion is, which provides a penalty to the target's Awareness-intuition skill check to realize he's seeing an illusion: Ordinary, +1; Good, +2; Amazing, +3. Multiple targets provide a cumulative +1 penalty per extra target.",
	90104: "This skill can't be used untrained. This skill allows the user to direct a powerful blast of pure mental energy at another mind. The target must be within visual contact and no more than 40 meters away (range 10/20/40). Penalties for medium and long range are +1 and +2 respectively. Damage depends on the result of a skill check and the user's rank in the skill. Armor doesn't protect against a mind blast. When a character first acquires this skill, he is able to cause damage of d4+1s/d4+2s/d6+2s. Increased Damage: At rank 5, damage becomes d4+2s/d6+2s/d8+2s. At rank 9, the damage caused by the skill goes to 2d4+2s/2d6+2s/2d8+2s.",
	90105: "This skill allows a character to establish a mental defense against psionic powers: contact, empathy, illusion, mind reading, mind blast, suggest, and tire. A mind shield provides a penalty to the skill check of another psionic character attempting to use any of these skills: Ordinary, +1; Good, +2; Amazing, +3. These penalties are cumulative with any other resistances. The shield remains in place for d4+4 hours or until it fails to stop a psionic power directed against it.",
	90106: "This specialty skill allows a character to mesmerize another character, planting a thought into their mind and convincing them that the thought is her own. No suggestion can have a permanent or immediately detrimental effect. A suggestion lasts for as long as 1, 2, or 3 hours (Ordinary, Good, or Amazing). The GM assigns a bonus or a penalty based on extremity (+3 or more penalty for opposed to nature, -1 or -2 bonus for inclined acts). The target is entitled to a Will check after suggest wears off to realize they were suggesting, with a modifier that is the reverse of the situation die used for the skill check.",
	90107: "This skill inflicts fatigue damage upon a target. The target must be within visual contact and no more than 30 meters away (range 10/20/30). Penalties for medium and long range are +1 and +2 respectively. The amount of damage inflicted depends on the result of a skill check: Ordinary, 1 fatigue point; Good, 2 points; Amazing, 3 points.",
	90201: "This skill can't be used untrained. With this skill, a character can cause an electrical charge to build up in the air around him, and he can direct that charge up to 16 meters away (range 4/8/16), delivering a shock to a single target. During the phase in which the character makes a successful skill check, the charge builds up. It can be released (for no added point cost) in any phase after that during the current round or the next one, but discharging the energy requires an additional skill check. If the charge is not released, it simply dissipates. The character can't initiate any other psionic skill while the charge is present around his body. The amount of energy damage caused by the shock depends on the result of the skill check made when it is discharged and the character's rank in the skill. When a character first acquires this skill, he is able to cause damage of d4+2s/d6+2s/d4w. Increased Damage: At rank 5, damage becomes d6+2s/d4w/d4+2w. At rank 9, the damage caused by the skill goes to d4+2w/d6+2w/d8+2w.",
	90202: "Extended duration. This skill can't be used untrained. This skill allows a character to create an invisible defensive barrier that moves with him and provides protection from physical attacks (high impact or low impact damage) by manipulating the air molecules around him. The barrier is so close to his body that it doesn't hinder other actions the hero might take. The quality of the shield depends on the result of a skill check: Ordinary, HI +1/LI +2; Good, HI +2/LI +3; Amazing, HI +3/LI +4. If the shielded character wants to perform other actions while maintaining the shield, those actions receive a +1 penalty due to the character's need to concentrate on maintaining the shield.",
	90203: "Extended duration. This skill allows a character, with only the power of his mind, to lift himself into the air and propel himself as though he were flying. How high and how fast a character can move while levitating depends on the result of a skill check, as shown below. The first entry is how many meters he can ascend or descend per phase, the second is the speed at which he can fly. These figures are doubled in gravity conditions lighter than Earth normal and halved in gravity conditions heavier than Earth normal: Ordinary: 2 meters/walk x 1; Good: 4 meters/walk x 1.5; Amazing: 6 meters/walk x 2. If a character chooses to stop levitating or runs out of psionic energy points while he's out of touch with the ground, he suffers damage from a fall as indicated on TABLE P15: IMPACT DAMAGE. Performing an additional action while levitating provides a +1 penalty to that action.",
	90204: "With this skill, a character can excite the molecules in an object so that they give off illumination. It takes one phase for the object to reach maximum luminosity, and the molecules remain excited for the rest of the current round and all of the next round. The object provides Ordinary light (roughly the same as normal daylight) that illuminates an area of up to 6 meters in diameter, depending on the result of a skill check: Ordinary, 2 meters; Good, 4 meters; Amazing, 6 meters.",
	90205: "Extended duration. This skill is the ability to move objects using the power of the mind. A character can lift objects that weigh a number of kilograms equal to his Will score x 10, or push objects that weigh his Will score x 20 in kilograms. How high and how fast an object can move while being influenced by psychokinetics depends on the result of a skill check. The first entry is how many meters an object can be lifted, the second is the speed at which it can be pushed, both in meters per phase (doubled in light gravity, halved in heavy gravity): Ordinary: Lift 1 / Push 2; Good: Lift 2 / Push 4; Amazing: Lift 3 / Push 6. If a character chooses to stop using psychokinetics or runs out of psionic energy points while the object he's manipulating is out of touch with the ground, the object immediately falls and suffers damage as indicated on TABLE P15: IMPACT DAMAGE.",
	90206: "This skill can't be used untrained. This skill allows a character to excite molecules within an object or even in the air until enough heat is generated to cause the object or area to burst into flame. In the phase following a successful skill check, the target catches fire and sustains energy damage (range 10/20/30). Armor provides protection against this attack form. If the user targets the air around a character or object, the result is a flash fire storm that has an effect similar to that of an incendiary grenade. Objects and characters up to 6 meters away from the blast can be hurt, but the fire is less intense. The primary and secondary damage from this use of pyrokinetics, as indicated by the psionics-user's rank and skill check, is reduced by 2 points for targets within 2 meters of the blast, by 3 points for targets out to 4 meters away, and by 4 points for targets out to 6 meters away. If a character or object is targeted, the result is an intense burn from the initial damage and the possibility of the character or object catching fire and taking more damage in every phase thereafter until the fire goes out or is extinguished. The intensity of the fire depends on the result of a skill check and the character's rank in the skill. When a character first acquires this skill, he is able to cause damage of d4+2w/d6+2w/d8+2w. Increased Damage: At rank 5, damage becomes d6+2w/d8+2w/d4m. At rank 9, the damage caused by the skill goes to d8+2w/d4m/d4+2m.",
	90301: "Extended duration. This skill can't be used untrained. To use this skill, a hero focuses on the battle at hand and makes a skill check. The success achieved indicates the benefit he receives while the current application of the skill remains active. A successful skill check gives the hero a bonus to his action checks: Ordinary, -1; Good, -2; Amazing, -3.",
	90302: "With this skill, a hero selects a location and projects his mind to that spot, hearing sounds as though he was physically there. Clairaudience doesn't screen out noise around the user, so he might have trouble hearing what's going on at a distance. It provides no help in interpreting unknown languages or recognizing unfamiliar sounds, and the mental ear can't move from the location it's projected to. Because the user remains conscious within his body, he is aware of what's happening around his body. The better the result of the skill check, the longer the ability lasts: Ordinary, 1 round; Good, 2 rounds; Amazing, 3 rounds. This duration can be extended by spending 1 psionic energy point for every additional round. Situation modifiers apply.",
	90303: "To employ this skill, a hero selects a location and projects his mind to that spot. He can then see everything going on around that spot as though he was physically there. This projection must be to an unobstructed location, not to a place inside a solid object. The use of the skill doesn't block the user's normal vision, so he sees double images unless he closes his eyes. It also provides no help in seeing through obscuring elements, such as walls, closed doors, or darkness, and the mental eye can't move from the selected spot. Because the user remains conscious within his body, he is aware of what's happening around his body. The better the result of the skill check, the longer the ability lasts: Ordinary, 1 round; Good, 2 rounds; Amazing, 3 rounds. This duration can be extended by spending 1 psionic energy point for every additional round. Situation modifiers apply.",
	90304: "This skill allows a hero to \"read\" the surface emotions of another character. This ability assists the user in encounter situations. The skill user must be in visual contact with the target. A successful use of empathy provides a character with an understanding of the target's emotional state (Combative, Hostile, Neutral, Friendly, Charmed, or Fanatic) and provides a bonus when using encounter skills upon that target character (-1, -2, or -3 steps, depending on the degree of success achieved).",
	90305: "This skill enables a hero to \"read\" the surface thoughts of another character with whom the user is in visual contact. The mental contact remains in effect for a limited time and can't be extended by the use of psionic energy points. The better the degree of success achieved, the longer the contact lasts and the clearer the impressions of the thoughts being read: On an Ordinary success, the contact lasts for 1 phase after the skill check is made. Only random and disjointed thoughts are perceived, such as the target's name or the identity of someone or something he is thinking about or looking at. On a Good success, the contact lasts for 2 phases after the skill check is made. In addition to random thoughts, more detail and more coherence is received, such as why the target is thinking about someone or something, or why the target is in his present location. On an Amazing success, the contact lasts for 3 phases after the skill check is made. Complete surface thoughts can be read—the sort of information that's recovered on an Ordinary or Good success, plus some key fact that's related to what the psionics-user hoped to discover.",
	90306: "This skill can't be used untrained. A character who uses this skill can instinctively determine his present location and mentally plot a course to a distant location. This can be accomplished on a planetary surface, in normal space, and even through drivespace, depending on how the character applies this skill. This mental ability replaces the use of the Navigation skill (if the character has it) whenever the character decides to spend psionic energy points. All the modifiers that pertain to the use of the Navigation skill apply, except the character doesn't make use of charts, instruments, or computers to determine his location and plot courses. At rank 1, the character selects one specialty of the Navigation skill to which to apply this mental ability, either surface navigation, system astrogation, or drivespace astrogation. Extra Specialty Skills: At rank 5, a second Navigation specialty can be selected. At rank 9, the remaining specialty becomes available.",
	90307: "With this skill, a character can sense the mood of an area and even \"see\" events that happened there in the recent past. What a character senses depends on the result of a skill check: On an Ordinary success, the character senses general emotions that have been left in an area. On a Good success, he also receives brief flashes of events that may or may not make sense to him. On an Amazing success, he actually experiences a brief encounter as though he were at the scene when the events occurred. One successful skill check can be made in an area, and only recent events can be revealed. In general, a character can see a number of time units (usually hours or days) into the past equal to his skill rank. (With just the broad skill, less than one time unit is available to the character.) This skill can be used by a player to gain clues for his hero, or it can be used by the Gamemaster to provide clues or direct story elements in a certain direction. The Gamemaster can automatically activate this skill (no psionic energy point cost) to provide clues.",
	90308: "This skill is the ability to receive impressions about possible future events—what the psionics-user sees will probably happen if he takes no action to change it. A character usually doesn't consciously employ this skill. Instead, the Gamemaster calls for a character to make a skill check whenever a precognitive flash might occur. If the character is not willing to spend psionic energy points to make the skill check, nothing happens and the scene continues. What a character senses depends on the result of a skill check: On an Ordinary success, the character perceives vague images of a future event. On a Good success, he receives brief flashes of coming events that may or may not make sense to him. On an Amazing success, he actually experiences a brief encounter as though he is at the scene when the events transpire. In general, a character can see a number of hours or days into the future equal to his skill rank. (With the broad skill, less than one hour or day is available to the character.) If a character wants to force a precognitive flash, the cost in psionic energy points is doubled—2 points to use the specialty skill, 4 points if he has only the broad skill, and 6 points if the check results in a Critical Failure. In addition, a +3 penalty is applied, and whether the check succeeds or not, the skill can't be used again consciously for 2d6 days.",
	90309: "This skill gives a hero the ability to read psychic impressions from inanimate objects. The character must touch the object to gain insight into who has used it and in what context. What a character senses depends on the result of a skill check: On an Ordinary success, the character receives simple emotions associated with the object. On a Good success, he receives simple images associated with the object. On an Amazing success, he experiences a brief encounter as though he is the person using the object or its owner. To be affected by this skill, an object must be an item that the character can hold and manipulate to pick up psionic impressions. Dirt, the ground, dust, or other casually encountered objects aren't affected because people don't make the sorts of connections with these objects that result in psionic residue being left behind (though postcognition picks up impressions left in an area). The Gamemaster can automatically activate this skill (no psionic energy point cost) to provide a clue or otherwise direct a story.",
	90310: "This skill enables a hero to realize when a psionic skill is being used in his or her vicinity. Unlike the Psionic Awareness perk, the sensitivity specialty is consciously invoked by the hero whenever he or she desires to do so, and the check to determine success is made by the player of the hero, not by the Gamemaster. Activating the skill requires the hero to use 2 psionic energy points. The sensitivity persists for 1 minute, and can be kept active in subsequent minutes by expending 1 psionic energy point per minute thereafter. The skill check made when the specialty is first invoked determines the extent of what the hero learns during all the time when the specialty remains in use: On an Ordinary success, the hero becomes aware that one or more psionic skills are being employed within a range of 20 meters, and can tell which character(s) the psionic energy is emanating from. A Good success also enables the hero to identify the broad skill(s) being used, and an Amazing success tells the hero the exact specialty skill(s) being used. (The use of sensitivity can itself be detected by another character who successfully employs the skill.)"
}

const COMPLEX_SKILL_NOTES := {
	4: "Long climbs and challenge-scene climbing can be run as complex checks.",
	27: "Opening difficult locks can require a complex check; complexity depends on the lock and conditions.",
	62: "Hacking commonly uses a complex check against the target system's security.",
	64: "Writing or modifying software can use a complex check over time.",
	66: "Disarming explosives can use a complex check when the device is complicated or dangerous.",
	67: "Scratch-built explosives can require multiple successes to assemble safely.",
	89: "Surgery is normally handled as a complex medical task.",
	90: "Treatment can require a complex check for serious injuries or extended care.",
	115: "Invention is a complex technical task whose successes represent progress toward a working design.",
	117: "Major repairs can use complex checks; time and required successes depend on damage and equipment.",
	124: "Animal training uses complex checks; harder training takes more successes and more time.",
	133: "Tracking a long or difficult trail can use complex checks; failures can lose the trail.",
	145: "First encounter scenes can use complex checks to build understanding and avoid offense.",
	156: "Important bargaining can be run as a social complex check.",
	157: "Extended attempts to win trust can use complex social checks.",
	158: "Interviews can use complex checks when the information is hard to draw out.",
	160: "Extended seduction or influence attempts can use complex social checks.",
}

const RANK_BENEFIT_NOTES := {
	1: {
		1: "Armor penalties for the appropriate armor type are reduced by 1 additional step beyond the broad skill reduction. Source: Player's Handbook p. 66.",
		2: "Stun damage suffered while wearing the appropriate armor type is reduced by 1 point. Source: Player's Handbook p. 66.",
		4: "Armor penalty reduction improves to 2 additional steps, and armor-worn stun reduction improves to 2 points. These reductions never create a bonus. Source: Player's Handbook p. 66.",
		6: "Armor-worn stun reduction improves to 3 points. Source: Player's Handbook p. 66.",
		7: "Armor penalty reduction improves to 3 additional steps. These reductions never create a bonus. Source: Player's Handbook p. 66.",
		8: "Armor-worn stun reduction improves to 4 points. Source: Player's Handbook p. 66.",
		10: "Armor penalty reduction improves to 4 additional steps, and armor-worn stun reduction improves to 5 points. Source: Player's Handbook p. 66.",
		12: "Armor-worn stun reduction reaches 6 points. Source: Player's Handbook p. 66.",
	},
	2: {
		1: "Armor penalties for the appropriate armor type are reduced by 1 additional step beyond the broad skill reduction. Source: Player's Handbook p. 66.",
		2: "Stun damage suffered while wearing the appropriate armor type is reduced by 1 point. Source: Player's Handbook p. 66.",
		4: "Armor penalty reduction improves to 2 additional steps, and armor-worn stun reduction improves to 2 points. These reductions never create a bonus. Source: Player's Handbook p. 66.",
		6: "Armor-worn stun reduction improves to 3 points. Source: Player's Handbook p. 66.",
		7: "Armor penalty reduction improves to 3 additional steps. These reductions never create a bonus. Source: Player's Handbook p. 66.",
		8: "Armor-worn stun reduction improves to 4 points. Source: Player's Handbook p. 66.",
		10: "Armor penalty reduction improves to 4 additional steps, and armor-worn stun reduction improves to 5 points. Source: Player's Handbook p. 66.",
		12: "Armor-worn stun reduction reaches 6 points. Source: Player's Handbook p. 66.",
	},
	5: {
		3: "Running jump distance increases by 1 meter. Source: Player's Handbook p. 67.",
		4: "Standing jump distance increases by 1 meter. Source: Player's Handbook p. 67.",
		5: "Vertical jump distance increases by 0.5 meter. Source: Player's Handbook p. 67.",
		6: "Running jump distance increases by another 1 meter. Source: Player's Handbook p. 67.",
		7: "Standing jump distance increases by another 1 meter. Source: Player's Handbook p. 67.",
		8: "Vertical jump distance increases by another 0.5 meter. Source: Player's Handbook p. 67.",
		9: "Running jump distance increases by another 1 meter. Source: Player's Handbook p. 67.",
		10: "Standing jump distance increases by another 1 meter. Source: Player's Handbook p. 67.",
		11: "Vertical jump distance increases by another 0.5 meter. Source: Player's Handbook p. 67.",
		12: "Running jump distance increases by another 1 meter. Source: Player's Handbook p. 67.",
	},
	12: {
		4: "Strength resistance modifier improves by +1 for close-combat defense, and reaction parry becomes available. Source: Player's Handbook p. 68.",
		6: "Double-strike becomes available: two attacks in one phase with one control die and two situation dice at +1 and +2 step penalties. Source: Player's Handbook p. 68.",
		8: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 68.",
		9: "Multistrike becomes available: three attacks in one phase, with +1, +2, and +3 step penalties on the situation dice. Source: Player's Handbook p. 68.",
		12: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 68.",
	},
	13: {
		4: "Strength resistance modifier improves by +1 for close-combat defense, and reaction parry becomes available. Source: Player's Handbook p. 68.",
		6: "Double-strike becomes available: two attacks in one phase with one control die and two situation dice at +1 and +2 step penalties. Source: Player's Handbook p. 68.",
		8: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 68.",
		9: "Multistrike becomes available: three attacks in one phase, with +1, +2, and +3 step penalties on the situation dice. Source: Player's Handbook p. 68.",
		12: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 68.",
	},
	14: {
		4: "Strength resistance modifier improves by +1 for close-combat defense, and reaction parry becomes available. Source: Player's Handbook p. 68.",
		6: "Double-strike becomes available: two attacks in one phase with one control die and two situation dice at +1 and +2 step penalties. Source: Player's Handbook p. 68.",
		8: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 68.",
		9: "Multistrike becomes available: three attacks in one phase, with +1, +2, and +3 step penalties on the situation dice. Source: Player's Handbook p. 68.",
		12: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 68.",
	},
	16: {
		4: "Knockout attempts impose a +1 step penalty on the opponent's Stamina-endurance check after an Amazing success. Source: Player's Handbook p. 69.",
		8: "Knockout penalty improves to +2 steps, and unarmed damage improves to d6s/d6+2s/d4w before Strength bonuses. Source: Player's Handbook p. 69.",
		12: "Knockout penalty improves to +3 steps. Source: Player's Handbook p. 69.",
	},
	17: {
		3: "Knockout attempts impose a +1 step penalty on the opponent's Stamina-endurance check after an Amazing success. Source: Player's Handbook p. 69.",
		4: "Strength resistance modifier improves by +1 for close-combat defense. Source: Player's Handbook p. 70.",
		5: "Can make Unarmed Attack checks even when hands are bound, cuffed, or unusable. Source: Player's Handbook p. 69.",
		6: "Knockout penalty improves to +2 steps. Source: Player's Handbook p. 69.",
		7: "Unarmed damage improves to d6+2s/d4w/d4+2w before Strength bonuses. Source: Player's Handbook p. 69.",
		8: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 70.",
		9: "Knockout penalty improves to +3 steps. Source: Player's Handbook p. 69.",
		12: "Strength resistance modifier improves by another +1 for close-combat defense, and knockout penalty improves to +4 steps. Source: Player's Handbook p. 69-70.",
	},
	20: {
		2: "Can block or counter unarmed attacks with Defensive Martial Arts. Source: Player's Handbook p. 71.",
		4: "Can attempt a reaction block against unarmed attacks, using the next available action; Strength resistance modifier improves by +1 for close-combat defense. Source: Player's Handbook p. 71.",
		8: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 71.",
		12: "Strength resistance modifier improves by another +1 for close-combat defense. Source: Player's Handbook p. 71.",
	},
	21: {
		3: "Can dodge and still take an action in the same phase; the action carries a +2 step penalty. Source: Player's Handbook p. 71.",
		4: "Dexterity resistance modifier improves by +1 against ranged combat. Source: Player's Handbook p. 71.",
		7: "Can perform a reaction dodge immediately, but gives up other actions for the round. Source: Player's Handbook p. 71.",
		8: "Dexterity resistance modifier improves by another +1 against ranged combat. Source: Player's Handbook p. 71.",
		12: "Dexterity resistance modifier improves by another +1 against ranged combat. Source: Player's Handbook p. 71.",
	},
	23: {
		3: "Glide movement improves by +2 meters. Source: Player's Handbook p. 71.",
		4: "Fly movement improves by +3 meters. Source: Player's Handbook p. 71.",
		7: "Glide movement improves by another +2 meters. Source: Player's Handbook p. 71.",
		8: "Fly movement improves by another +3 meters. Source: Player's Handbook p. 71.",
		11: "Glide movement improves by another +2 meters. Source: Player's Handbook p. 71.",
		12: "Fly movement improves by another +3 meters. Source: Player's Handbook p. 71.",
	},
	24: {
		1: "Zero-g penalty is reduced to +2 steps, and light-gravity penalties are eliminated. Source: Player's Handbook p. 72.",
		4: "Zero-g penalty is reduced to +1 step, and light-gravity physical actions gain a -1 step bonus. Source: Player's Handbook p. 72.",
		7: "Zero-g penalty is eliminated. Source: Player's Handbook p. 72.",
		10: "Zero-g physical actions gain a -1 step bonus. Source: Player's Handbook p. 72.",
	},
	28: {
		3: "Targets suffer a +1 step penalty to notice a pickpocket attempt. Source: Player's Handbook p. 72.",
		6: "Targets suffer a +2 step penalty to notice a pickpocket attempt. Source: Player's Handbook p. 72.",
		9: "Targets suffer a +3 step penalty to notice a pickpocket attempt. Source: Player's Handbook p. 72.",
		12: "Targets suffer a +4 step penalty to notice a pickpocket attempt. Source: Player's Handbook p. 72.",
	},
	31: {
		3: "Quick Draw removes the usual +1 step penalty for drawing and firing a pistol in the same phase. Source: Player's Handbook p. 73.",
		6: "Double-Shot allows two pistol shots in one action; the first shot uses a +1 step penalty and the second uses a +2 step penalty. Source: Player's Handbook p. 75.",
	},
	32: {
		3: "Improved Aim grants a -1 step bonus to rifle attacks. Source: Player's Handbook p. 73.",
		5: "Distance Precision removes the medium-range penalty and reduces the long-range penalty by 1 step for rifle attacks. Source: Player's Handbook p. 75.",
		6: "Precision Shooting reduces autofire attack penalties to 0, +1, and +2 steps. Source: Player's Handbook p. 73.",
	},
	33: {
		3: "Rock-n-Roll reduces the penalty for changing a clip and firing an SMG in the same action to +1 step. Source: Player's Handbook p. 73.",
		6: "Precision Shooting reduces autofire attack penalties to 0, +1, and +2 steps. Source: Player's Handbook p. 73.",
		9: "Extra Burst allows four bursts on autofire; the fourth situation die has a +3 step penalty and uses one additional burst. Source: Player's Handbook p. 73.",
	},
	35: {
		3: "Distance Precision removes the medium-range penalty and reduces the long-range penalty by 1 step for bow attacks. Source: Player's Handbook p. 75.",
		6: "Double-Shot allows two bow shots in one action; the first shot uses a +1 step penalty and the second uses a +2 step penalty. Source: Player's Handbook p. 75.",
	},
	36: {
		3: "Distance Precision removes the medium-range penalty and reduces the long-range penalty by 1 step for crossbow attacks. Source: Player's Handbook p. 75.",
		6: "Rate of Fire Increase lets a crossbow be loaded and fired in the same action. Source: Player's Handbook p. 75.",
	},
	37: {
		3: "Distance Precision removes the medium-range penalty and reduces the long-range penalty by 1 step for flintlock attacks. Source: Player's Handbook p. 75.",
		6: "Rate of Fire Increase lets a flintlock pistol be loaded and fired in the same action, and lets a flintlock rifle be loaded in one action. Source: Player's Handbook p. 75.",
		12: "Rate of Fire Increase lets a flintlock rifle be loaded and fired in the same action. Source: Player's Handbook p. 75.",
	},
	38: {
		3: "Distance Precision removes the medium-range penalty and reduces the long-range penalty by 1 step for sling attacks. Source: Player's Handbook p. 75.",
		6: "Double-Shot allows two sling shots at a single target in one action; the shots use +1 and +2 step penalties. Source: Player's Handbook p. 75.",
	},
	40: {
		4: "Stealth Increased Effect applies to Hide: Marginal/Ordinary/Good/Amazing results impose +1/+2/+3/+4 step observer penalties. Source: Player's Handbook p. 75.",
	},
	41: {
		5: "Stealth Increased Effect applies to Shadow: Marginal/Ordinary/Good/Amazing results impose +1/+2/+3/+4 step observer penalties. Source: Player's Handbook p. 75.",
	},
	42: {
		6: "Stealth Increased Effect applies to Sneak: Marginal/Ordinary/Good/Amazing results impose +1/+2/+3/+4 step observer penalties. Source: Player's Handbook p. 75.",
	},
	49: {
		1: "Run movement improves by +2 meters. Source: Player's Handbook p. 77.",
		4: "Sprint movement improves by +2 meters. Source: Player's Handbook p. 77.",
		5: "Run movement improves by another +2 meters. Source: Player's Handbook p. 77.",
		7: "Sprint movement improves by another +2 meters. Source: Player's Handbook p. 77.",
		9: "Run movement improves by another +2 meters. Source: Player's Handbook p. 77.",
		12: "Sprint movement improves by another +2 meters. Source: Player's Handbook p. 77.",
	},
	50: {
		1: "Stamina-endurance checks for holding breath or avoiding underwater stun damage gain a -1 step bonus. Source: Player's Handbook p. 77.",
		4: "Breath-holding bonus improves to -2 steps, and swim/easy swim movement each increase by 1 meter. Source: Player's Handbook p. 77.",
		8: "Breath-holding bonus improves to -3 steps, and swim/easy swim movement each increase by another 1 meter. Source: Player's Handbook p. 77.",
		12: "Breath-holding bonus improves to -4 steps, and swim/easy swim movement each increase by another 1 meter. Source: Player's Handbook p. 77.",
	},
	59: {
		1: "Illegal-transaction penalties are reduced by 1 step; this can eliminate but never create a bonus. Source: Player's Handbook p. 79.",
		4: "Illegal-transaction penalty reduction improves to 2 steps. Source: Player's Handbook p. 79.",
		7: "Illegal-transaction penalty reduction improves to 3 steps. Source: Player's Handbook p. 79.",
		10: "Illegal-transaction penalty reduction improves to 4 steps. Source: Player's Handbook p. 79.",
	},
	60: {
		1: "Small-business deals, haggling, and small-business finances gain a -1 step bonus. Source: Player's Handbook p. 79.",
		4: "Small-business bonus improves to -2 steps. Source: Player's Handbook p. 79.",
		8: "Small-business bonus improves to -3 steps. Source: Player's Handbook p. 79.",
		12: "Small-business bonus improves to -4 steps. Source: Player's Handbook p. 79.",
	},
	62: {
		4: "Hacking checks gain a -1 step bonus. Source: Player's Handbook p. 80.",
		8: "Hacking checks gain a -2 step bonus. Source: Player's Handbook p. 80.",
		12: "Hacking checks gain a -3 step bonus. Source: Player's Handbook p. 80.",
	},
	63: {
		4: "Hardware checks gain a -1 step bonus. Source: Player's Handbook p. 80.",
		8: "Hardware checks gain a -2 step bonus. Source: Player's Handbook p. 80.",
		12: "Hardware checks gain a -3 step bonus. Source: Player's Handbook p. 80.",
	},
	64: {
		1: "Can modify source code of Ordinary quality and Ordinary complexity. Source: Player's Handbook p. 80.",
		3: "Can modify existing programs of Good quality/complexity and create new programs of Marginal quality/complexity. Source: Player's Handbook p. 80.",
		6: "Can modify any existing program and create Ordinary quality/complexity programs. Source: Player's Handbook p. 80.",
		9: "Can create Good quality/complexity programs. Source: Player's Handbook p. 80.",
		12: "Can create Amazing quality/complexity programs. Source: Player's Handbook p. 80.",
	},
	71: {
		4: "Intelligence resistance modifier improves by +1. Source: Player's Handbook p. 82.",
		8: "Intelligence resistance modifier improves by another +1. Source: Player's Handbook p. 82.",
		12: "Intelligence resistance modifier improves by another +1. Source: Player's Handbook p. 82.",
	},
	72: {
		4: "First-aid situation penalties are reduced by 1 step; this can eliminate but never create a bonus. Source: Player's Handbook p. 82.",
		8: "First-aid situation penalty reduction improves to 2 steps. Source: Player's Handbook p. 82.",
		12: "First-aid situation penalty reduction improves to 3 steps. Source: Player's Handbook p. 82.",
	},
	73: {
		1: "Communication in the language carries a +3 step penalty. Source: Player's Handbook p. 83.",
		2: "Communication penalty improves to +1 step. Source: Player's Handbook p. 83.",
		3: "Communication has no language-rank modifier. Source: Player's Handbook p. 83.",
		6: "Communication in the language gains a -1 step bonus. Source: Player's Handbook p. 83.",
		9: "Communication in the language gains a -2 step bonus. Source: Player's Handbook p. 83.",
		12: "Communication in the language gains a -3 step bonus. Source: Player's Handbook p. 83.",
	},
	78: {
		3: "Checks involving this legal system gain a -1 step bonus when using Law, court procedures, or law enforcement as appropriate. Source: Player's Handbook p. 84.",
		6: "Legal-system bonus improves to -2 steps. Source: Player's Handbook p. 84.",
		9: "Legal-system bonus improves to -3 steps. Source: Player's Handbook p. 84.",
		12: "Legal-system bonus improves to -4 steps. Source: Player's Handbook p. 84.",
	},
	80: {
		3: "Checks assisted by Biology gain a -1 step bonus. Source: Player's Handbook p. 84.",
		6: "Biology-assisted bonus improves to -2 steps. Source: Player's Handbook p. 84.",
		9: "Biology-assisted bonus improves to -3 steps. Source: Player's Handbook p. 84.",
		12: "Biology-assisted bonus improves to -4 steps. Source: Player's Handbook p. 84.",
	},
	81: {
		3: "Checks assisted by Botany gain a -1 step bonus. Source: Player's Handbook p. 84.",
		6: "Botany-assisted bonus improves to -2 steps. Source: Player's Handbook p. 84.",
		9: "Botany-assisted bonus improves to -3 steps. Source: Player's Handbook p. 84.",
		12: "Botany-assisted bonus improves to -4 steps. Source: Player's Handbook p. 84.",
	},
	82: {
		3: "Checks assisted by Genetics gain a -1 step bonus. Source: Player's Handbook p. 84.",
		6: "Genetics-assisted bonus improves to -2 steps. Source: Player's Handbook p. 84.",
		9: "Genetics-assisted bonus improves to -3 steps. Source: Player's Handbook p. 84.",
		12: "Genetics-assisted bonus improves to -4 steps. Source: Player's Handbook p. 84.",
	},
	83: {
		3: "Checks assisted by Xenology gain a -1 step bonus. Source: Player's Handbook p. 84.",
		6: "Xenology-assisted bonus improves to -2 steps. Source: Player's Handbook p. 84.",
		9: "Xenology-assisted bonus improves to -3 steps. Source: Player's Handbook p. 84.",
		12: "Xenology-assisted bonus improves to -4 steps. Source: Player's Handbook p. 84.",
	},
	84: {
		3: "Checks assisted by Zoology gain a -1 step bonus. Source: Player's Handbook p. 84.",
		6: "Zoology-assisted bonus improves to -2 steps. Source: Player's Handbook p. 84.",
		9: "Zoology-assisted bonus improves to -3 steps. Source: Player's Handbook p. 84.",
		12: "Zoology-assisted bonus improves to -4 steps. Source: Player's Handbook p. 84.",
	},
	86: {
		3: "Checks assisted by Forensics gain a -1 step bonus. Source: Player's Handbook p. 85.",
		6: "Forensics-assisted bonus improves to -2 steps. Source: Player's Handbook p. 85.",
		9: "Forensics-assisted bonus improves to -3 steps. Source: Player's Handbook p. 85.",
		12: "Forensics-assisted bonus improves to -4 steps. Source: Player's Handbook p. 85.",
	},
	87: {
		2: "Medical Science-treatment checks gain a -1 step bonus. Source: Player's Handbook p. 85.",
		5: "Treatment-support bonus improves to -2 steps. Source: Player's Handbook p. 85.",
		8: "Treatment-support bonus improves to -3 steps. Source: Player's Handbook p. 85.",
		12: "Treatment-support bonus improves to -4 steps. Source: Player's Handbook p. 85.",
	},
	88: {
		3: "Checks assisted by Psychology gain a -1 step bonus. Source: Player's Handbook p. 85.",
		6: "Psychology-assisted bonus improves to -2 steps. Source: Player's Handbook p. 85.",
		9: "Psychology-assisted bonus improves to -3 steps. Source: Player's Handbook p. 85.",
		12: "Psychology-assisted bonus improves to -4 steps. Source: Player's Handbook p. 85.",
	},
	89: {
		3: "Cybernetic Surgery allows repair or healing of organisms with existing cybernetic implants when the campaign includes cybertech. Source: Player's Handbook p. 86.",
		6: "Cybernetic Surgery allows installation of cybernetic implants when the campaign includes cybertech. Source: Player's Handbook p. 86.",
	},
	90: {
		3: "Treatment situation penalties are reduced by 1 step; this can eliminate but never create a bonus. Source: Player's Handbook p. 86.",
		6: "Treatment penalty reduction improves to 2 steps. Source: Player's Handbook p. 86.",
		9: "Treatment penalty reduction improves to 3 steps. Source: Player's Handbook p. 86.",
		12: "Treatment penalty reduction improves to 4 steps. Source: Player's Handbook p. 86.",
	},
	91: {
		3: "Alien-patient penalty is reduced from +3 steps to +2 steps for the selected species. Source: Player's Handbook p. 86.",
		6: "Alien-patient penalty is reduced to +1 step for the selected species. Source: Player's Handbook p. 86.",
		9: "Alien-patient penalty is eliminated for the selected species. Source: Player's Handbook p. 86.",
		12: "Treating the selected species gains a -1 step bonus. Source: Player's Handbook p. 86.",
	},
	97: {
		3: "Checks assisted by Astronomy gain a -1 step bonus. Source: Player's Handbook p. 88.",
		6: "Astronomy-assisted bonus improves to -2 steps. Source: Player's Handbook p. 88.",
		9: "Astronomy-assisted bonus improves to -3 steps. Source: Player's Handbook p. 88.",
		12: "Astronomy-assisted bonus improves to -4 steps. Source: Player's Handbook p. 88.",
	},
	98: {
		3: "Checks assisted by Chemistry gain a -1 step bonus. Source: Player's Handbook p. 88.",
		6: "Chemistry-assisted bonus improves to -2 steps. Source: Player's Handbook p. 88.",
		9: "Chemistry-assisted bonus improves to -3 steps. Source: Player's Handbook p. 88.",
		12: "Chemistry-assisted bonus improves to -4 steps. Source: Player's Handbook p. 88.",
	},
	99: {
		3: "Checks assisted by Physics gain a -1 step bonus. Source: Player's Handbook p. 88.",
		6: "Physics-assisted bonus improves to -2 steps. Source: Player's Handbook p. 88.",
		9: "Physics-assisted bonus improves to -3 steps. Source: Player's Handbook p. 88.",
		12: "Physics-assisted bonus improves to -4 steps. Source: Player's Handbook p. 88.",
	},
	100: {
		3: "Checks assisted by Planetology gain a -1 step bonus. Source: Player's Handbook p. 88.",
		6: "Planetology-assisted bonus improves to -2 steps. Source: Player's Handbook p. 88.",
		9: "Planetology-assisted bonus improves to -3 steps. Source: Player's Handbook p. 88.",
		12: "Planetology-assisted bonus improves to -4 steps. Source: Player's Handbook p. 88.",
	},
	111: {
		4: "Tactics checks against opposing infantry gain a -1 step bonus. Source: Player's Handbook p. 89.",
		8: "Infantry tactics bonus improves to -2 steps. Source: Player's Handbook p. 89.",
		12: "Infantry tactics bonus improves to -3 steps. Source: Player's Handbook p. 89.",
	},
	112: {
		4: "Tactics checks against opposing spaceships gain a -1 step bonus. Source: Player's Handbook p. 89.",
		8: "Space tactics bonus improves to -2 steps. Source: Player's Handbook p. 89.",
		12: "Space tactics bonus improves to -3 steps. Source: Player's Handbook p. 89.",
	},
	113: {
		4: "Tactics checks against opposing vehicles gain a -1 step bonus. Source: Player's Handbook p. 89.",
		8: "Vehicle tactics bonus improves to -2 steps. Source: Player's Handbook p. 89.",
		12: "Vehicle tactics bonus improves to -3 steps. Source: Player's Handbook p. 89.",
	},
	116: {
		6: "Improved Juryrig upgrades success quality: Ordinary functions as Good, Good as Amazing, and Amazing counts as a regular repair. Source: Player's Handbook p. 90.",
	},
	118: {
		3: "Checks involving Technical Science or its specialties gain a -1 step bonus. Source: Player's Handbook p. 90.",
		6: "Technical Science support bonus improves to -2 steps. Source: Player's Handbook p. 90.",
		9: "Technical Science support bonus improves to -3 steps. Source: Player's Handbook p. 90.",
		12: "Technical Science support bonus improves to -4 steps. Source: Player's Handbook p. 90.",
	},
	123: {
		3: "Trick Riding becomes available; mounted cover can impose opponent attack penalties of +1/+2/+3 steps on Ordinary/Good/Amazing riding results. Source: Player's Handbook p. 91-92.",
	},
	133: {
		1: "Select one terrain type when buying Track and one additional terrain type at each new rank; tracking in a selected terrain gains a -1 step bonus, while unselected terrain carries a +1 step penalty. Source: Player's Handbook p. 94.",
	},
	135: {
		4: "Will resistance modifier improves by +1 against encounter skills, mental powers, and similar influence. Source: Player's Handbook p. 94.",
		8: "Will resistance modifier improves by another +1 against encounter skills, mental powers, and similar influence. Source: Player's Handbook p. 94.",
		12: "Will resistance modifier improves by another +1 against encounter skills, mental powers, and similar influence. Source: Player's Handbook p. 94.",
	},
	144: {
		3: "Culture-diplomacy checks with the selected culture gain a -1 step bonus. Source: Player's Handbook p. 97.",
		6: "Selected-culture diplomacy bonus improves to -2 steps. Source: Player's Handbook p. 97.",
		9: "Selected-culture diplomacy bonus improves to -3 steps. Source: Player's Handbook p. 97.",
		12: "Selected-culture diplomacy bonus improves to -4 steps. Source: Player's Handbook p. 97.",
	},
	151: {
		1: "Can enhance an appropriate paired skill with a -1 step bonus when the GM agrees the Act performance applies. Source: Player's Handbook p. 99.",
		4: "Paired-skill enhancement improves to -2 steps, and Disguise becomes available as a complex Act check; observers suffer +1/+2/+3 step penalties on Ordinary/Good/Amazing disguises. Source: Player's Handbook p. 99.",
		8: "Paired-skill enhancement improves to -3 steps. Source: Player's Handbook p. 99.",
		12: "Paired-skill enhancement improves to -4 steps. Source: Player's Handbook p. 99.",
	},
	152: {
		1: "Can enhance an appropriate paired skill with a -1 step bonus when the GM agrees the Dance performance applies. Source: Player's Handbook p. 99.",
		4: "Paired-skill enhancement improves to -2 steps. Source: Player's Handbook p. 99.",
		8: "Paired-skill enhancement improves to -3 steps. Source: Player's Handbook p. 99.",
		12: "Paired-skill enhancement improves to -4 steps. Source: Player's Handbook p. 99.",
	},
	153: {
		1: "Can enhance an appropriate paired skill with a -1 step bonus when the GM agrees the Musical Instrument performance applies. Source: Player's Handbook p. 99.",
		4: "Paired-skill enhancement improves to -2 steps. Source: Player's Handbook p. 99.",
		8: "Paired-skill enhancement improves to -3 steps. Source: Player's Handbook p. 99.",
		12: "Paired-skill enhancement improves to -4 steps. Source: Player's Handbook p. 99.",
	},
	154: {
		1: "Can enhance an appropriate paired skill with a -1 step bonus when the GM agrees the Sing performance applies. Source: Player's Handbook p. 99.",
		4: "Paired-skill enhancement improves to -2 steps. Source: Player's Handbook p. 99.",
		8: "Paired-skill enhancement improves to -3 steps. Source: Player's Handbook p. 99.",
		12: "Paired-skill enhancement improves to -4 steps. Source: Player's Handbook p. 99.",
	},
	163: {
		4: "Leadership skill checks gain a -1 step bonus; Command and Inspire benefits do not stack with each other. Source: Player's Handbook p. 101.",
		8: "Leadership skill-check bonus improves to -2 steps; Command and Inspire benefits do not stack with each other. Source: Player's Handbook p. 101.",
		12: "Leadership skill-check bonus improves to -3 steps; Command and Inspire benefits do not stack with each other. Source: Player's Handbook p. 101.",
	},
	164: {
		4: "Leadership skill checks gain a -1 step bonus; Command and Inspire benefits do not stack with each other. Source: Player's Handbook p. 101.",
		8: "Leadership skill-check bonus improves to -2 steps; Command and Inspire benefits do not stack with each other. Source: Player's Handbook p. 101.",
		12: "Leadership skill-check bonus improves to -3 steps; Command and Inspire benefits do not stack with each other. Source: Player's Handbook p. 101.",
	},
	90003: {
		6: "Can heal mortal damage. Skill check results change to: Ordinary, 2 wounds; Good, 3 wounds or 1 mortal; Amazing, 4 wounds or 2 mortals. Source: Player's Handbook p. 229."
	},
	90004: {
		1: "Select one of these forms: Elongate fingers, adding one-half meter to reach. Elongate arms, adding 1 meter to reach. Elongate legs, adding 1 meter to height. Source: Player's Handbook p. 229-230.",
		3: "Select one of these forms: Elongate fingers, adding one-half meter to reach. Elongate arms, adding 1 meter to reach. Elongate legs, adding 1 meter to height. Source: Player's Handbook p. 229-230.",
		5: "Choose one of these forms: Disguise; alter one's facial features to hide identity (+2 penalty to Awareness checks involving an attempt to recognize the character). Elongate arms and legs simultaneously. Elongate entire body and alter bone construction to allow passage through small openings (as small as one-half meter wide). Source: Player's Handbook p. 229-230.",
		7: "Choose one of these forms: Disguise; alter one's facial features to hide identity (+2 penalty to Awareness checks involving an attempt to recognize the character). Elongate arms and legs simultaneously. Elongate entire body and alter bone construction to allow passage through small openings (as small as one-half meter wide). Source: Player's Handbook p. 229-230.",
		10: "Choose one of these forms: Improved disguise; alter facial and body features to hide identity (+4 penalty to Awareness checks). Lessen damage; body becomes so flexible and malleable as to reduce the effects of low impact damage. A skill check is made (at no psionic energy cost) to determine how much damage is reduced: Ordinary, d4; Good, d4+2; Amazing, d6+2. Note that this benefit isn't received if the character is wearing armor. Morph control; activate any two forms simultaneously. Source: Player's Handbook p. 229-230.",
		12: "Choose one of these forms: Improved disguise; alter facial and body features to hide identity (+4 penalty to Awareness checks). Lessen damage; body becomes so flexible and malleable as to reduce the effects of low impact damage. A skill check is made (at no psionic energy cost) to determine how much damage is reduced: Ordinary, d4; Good, d4+2; Amazing, d6+2. Note that this benefit isn't received if the character is wearing armor. Morph control; activate any two forms simultaneously. Source: Player's Handbook p. 229-230."
	},
	90104: {
		5: "Damage becomes d4+2s/d6+2s/d8+2s. Source: Player's Handbook p. 236.",
		9: "Damage caused by the skill goes to 2d4+2s/2d6+2s/2d8+2s. Source: Player's Handbook p. 236."
	},
	90201: {
		5: "Damage becomes d6+2s/d4w/d4+2w. Source: Player's Handbook p. 233.",
		9: "Damage caused by the skill goes to d4+2w/d6+2w/d8+2w. Source: Player's Handbook p. 233."
	},
	90206: {
		5: "Damage becomes d6+2w/d8+2w/d4m. Source: Player's Handbook p. 234.",
		9: "Damage caused by the skill goes to d8+2w/d4m/d4+2m. Source: Player's Handbook p. 234."
	},
	90306: {
		1: "Select one Navigation specialty (surface, system astrogation, or drivespace astrogation) to apply this mental ability. Source: Player's Handbook p. 232.",
		5: "A second Navigation specialty becomes available. Source: Player's Handbook p. 232.",
		9: "The remaining Navigation specialty becomes available. Source: Player's Handbook p. 232."
	}
}


const SKILL_SOURCE_REFERENCES := {
	0: ["Player's Handbook p. 66."],
	1: ["Player's Handbook p. 66."],
	2: ["Player's Handbook p. 66."],
	3: ["Player's Handbook p. 66-67."],
	8: ["Player's Handbook p. 68."],
	11: ["Player's Handbook p. 68-69."],
	12: ["Player's Handbook p. 68-69."],
	13: ["Player's Handbook p. 68-69."],
	14: ["Player's Handbook p. 68-69."],
	15: ["Player's Handbook p. 69-70.", "Gamemaster Guide, overpowering rules."],
	16: ["Player's Handbook p. 69."],
	17: ["Player's Handbook p. 69-70."],
	18: ["Player's Handbook p. 70-72."],
	26: ["Player's Handbook p. 72-73."],
	30: ["Player's Handbook p. 73-75."],
	34: ["Player's Handbook p. 74-75."],
	39: ["Player's Handbook p. 75."],
	43: ["Player's Handbook p. 76."],
	48: ["Player's Handbook p. 76-77."],
	52: ["Player's Handbook p. 77-78."],
	55: ["Player's Handbook p. 78."],
	57: ["Player's Handbook p. 79-80."],
	61: ["Player's Handbook p. 80-81.", "Gamemaster Guide p. 124-125 for computer challenges."],
	65: ["Player's Handbook p. 81."],
	69: ["Player's Handbook p. 81-83."],
	75: ["Player's Handbook p. 83-84."],
	79: ["Player's Handbook p. 84-85."],
	85: ["Player's Handbook p. 85-87."],
	92: ["Player's Handbook p. 87-88."],
	96: ["Player's Handbook p. 88."],
	101: ["Player's Handbook p. 89."],
	104: ["Player's Handbook p. 88-89."],
	110: ["Player's Handbook p. 89."],
	114: ["Player's Handbook p. 89-90."],
	119: ["Player's Handbook p. 90-91."],
	122: ["Player's Handbook p. 91-92."],
	125: ["Player's Handbook p. 92-93."],
	128: ["Player's Handbook p. 93."],
	130: ["Player's Handbook p. 93-94."],
	134: ["Player's Handbook p. 94-95."],
	137: ["Player's Handbook p. 95-96."],
	140: ["Player's Handbook p. 96."],
	142: ["Player's Handbook p. 97-98."],
	146: ["Player's Handbook p. 98-99."],
	150: ["Player's Handbook p. 99-100."],
	155: ["Player's Handbook p. 100-101."],
	162: ["Player's Handbook p. 101."],
	900: ["Player's Handbook p. 229."],
	90001: ["Player's Handbook p. 229."],
	90002: ["Player's Handbook p. 229."],
	90003: ["Player's Handbook p. 229."],
	90004: ["Player's Handbook p. 229-230."],
	90005: ["Player's Handbook p. 230."],
	90006: ["Player's Handbook p. 230."],
	901: ["Player's Handbook p. 234."],
	90101: ["Player's Handbook p. 235."],
	90102: ["Player's Handbook p. 235."],
	90103: ["Player's Handbook p. 235-236."],
	90104: ["Player's Handbook p. 236."],
	90105: ["Player's Handbook p. 236."],
	90106: ["Player's Handbook p. 236."],
	90107: ["Player's Handbook p. 236."],
	902: ["Player's Handbook p. 233."],
	90201: ["Player's Handbook p. 233."],
	90202: ["Player's Handbook p. 233-234."],
	90203: ["Player's Handbook p. 234."],
	90204: ["Player's Handbook p. 234."],
	90205: ["Player's Handbook p. 234."],
	90206: ["Player's Handbook p. 234."],
	903: ["Player's Handbook p. 230."],
	90301: ["Player's Handbook p. 230."],
	90302: ["Player's Handbook p. 230."],
	90303: ["Player's Handbook p. 230-231."],
	90304: ["Player's Handbook p. 231."],
	90305: ["Player's Handbook p. 231-232."],
	90306: ["Player's Handbook p. 232."],
	90307: ["Player's Handbook p. 232."],
	90308: ["Player's Handbook p. 232."],
	90309: ["Player's Handbook p. 232."],
	90310: ["Player's Handbook p. 233."]
}


const PERK_DEFINITIONS := [
	{
		"id": "alien_artifact",
		"name": "Alien Artifact",
		"cost_options": [8],
		"ability": "Special",
		"activation": "Special",
		"summary": "A GM-designed alien item, experiment, or process gives the hero a useful benefit, but it is rare, coveted, and carries a downside.",
		"source": "Player's Handbook p. 103-104; Table P26.",
	},
	{
		"id": "ambidextrous",
		"name": "Ambidextrous",
		"cost_options": [4],
		"ability": "DEX",
		"activation": "Active",
		"summary": "Reduces off-hand or two-weapon penalties: the primary hand has no penalty and the off-hand action has a +2 step penalty.",
		"source": "Player's Handbook p. 103-104; Table P26.",
	},
	{
		"id": "animal_friend",
		"name": "Animal Friend",
		"cost_options": [4],
		"ability": "WIL",
		"activation": "Conscious",
		"summary": "Normal animals trust the hero. Animal encounter rolls gain a -2 step bonus, and Animal Handling checks gain a -1 step bonus.",
		"source": "Player's Handbook p. 104; Table P26.",
	},
	{
		"id": "celebrity",
		"name": "Celebrity",
		"cost_options": [3],
		"ability": "PER",
		"activation": "Conscious",
		"summary": "The hero is famous in an agreed circle. A perk check can modify Personality-based checks in a scene from a penalty on bad results to bonuses on success; the base check improves at achievement levels 5, 10, and 15.",
		"source": "Player's Handbook p. 104-105; Table P26.",
	},
	{
		"id": "concentration",
		"name": "Concentration",
		"cost_options": [3],
		"ability": "INT",
		"activation": "Conscious",
		"summary": "The hero spends an action concentrating on a stated next task. Success grants a -1, -2, or -3 step bonus; interruption loses the bonus.",
		"source": "Player's Handbook p. 105; Table P26.",
	},
	{
		"id": "danger_sense",
		"name": "Danger Sense",
		"cost_options": [4],
		"ability": "WIL",
		"activation": "Active",
		"summary": "The hero anticipates danger and receives a -2 step bonus to Awareness-intuition checks.",
		"source": "Player's Handbook p. 105; Table P26.",
	},
	{
		"id": "faith",
		"name": "Faith",
		"cost_options": [5],
		"ability": "WIL",
		"activation": "Conscious",
		"summary": "The hero has deep faith in a belief, power, nation, or similar tenet. A qualifying Faith check can improve the degree of success of a later skill check; repeated use in an adventure becomes harder.",
		"source": "Player's Handbook p. 105; Table P26.",
	},
	{
		"id": "filthy_rich",
		"name": "Filthy Rich",
		"cost_options": [6],
		"ability": "PER",
		"activation": "Conscious",
		"summary": "The hero starts wealthy and may gain access to funds with a perk check. Revealing status can modify Personality-based checks, but the GM can invert the effect where wealth is a liability.",
		"source": "Player's Handbook p. 105-106; Table P26.",
	},
	{
		"id": "fists_of_iron",
		"name": "Fists of Iron",
		"cost_options": [2, 5],
		"ability": "STR",
		"activation": "Active",
		"summary": "Adds +1 damage to successful Unarmed Attack checks. The 5-point improved version requires power martial arts and can increase damage further based on a perk check.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "fortitude",
		"name": "Fortitude",
		"cost_options": [4],
		"ability": "CON",
		"activation": "Active",
		"summary": "The hero receives a -1 step bonus to Stamina-endurance checks.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "good_luck",
		"name": "Good Luck",
		"cost_options": [3],
		"ability": "WIL",
		"activation": "Conscious",
		"summary": "Once per scene before another action, a Good Luck check modifies that next activity. Poor results can impose bad luck; better results grant bonuses.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "great_looks",
		"name": "Great Looks",
		"cost_options": [3],
		"ability": "PER",
		"activation": "Active",
		"summary": "When appearance helps an encounter, the hero gains a -1 step bonus to Personality-based skill checks, subject to GM and cultural context.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "heightened_ability",
		"name": "Heightened Ability",
		"cost_options": [10],
		"ability": "Special",
		"activation": "Active",
		"summary": "Raises one Ability Score by 1, without exceeding the species maximum; update derived values as needed.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "observant",
		"name": "Observant",
		"cost_options": [3],
		"ability": "WIL",
		"activation": "Active",
		"summary": "The hero gains a -1 step bonus to Awareness-perception checks.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "photo_memory",
		"name": "Photo Memory",
		"cost_options": [3],
		"ability": "INT",
		"activation": "Conscious",
		"summary": "A perk check can let the hero recall details such as names, faces, documents, or other remembered information; the GM sets the situation die.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "powerful_ally",
		"name": "Powerful Ally",
		"cost_options": [4],
		"ability": "PER",
		"activation": "Conscious",
		"summary": "The hero has an agreed ally. A perk check determines the quality of aid if the hero can contact the ally and the ally can respond.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "psionic_awareness",
		"name": "Psionic Awareness",
		"cost_options": [3],
		"ability": "INT",
		"activation": "Active",
		"summary": "If psionics are allowed, the hero may receive an Intelligence feat check to notice psionic power use nearby.",
		"source": "Player's Handbook p. 106; Table P26.",
	},
	{
		"id": "reflexes",
		"name": "Reflexes",
		"cost_options": [4],
		"ability": "DEX",
		"activation": "Active",
		"summary": "The hero's Dexterity resistance modifier improves by 1 step.",
		"source": "Player's Handbook p. 107; Table P26.",
	},
	{
		"id": "reputation",
		"name": "Reputation",
		"cost_options": [3],
		"ability": "WIL",
		"activation": "Active",
		"summary": "A known reputation can grant a situation die bonus to agreed encounter skills. The base check improves at achievement levels 5, 10, and 15.",
		"source": "Player's Handbook p. 107; Table P26.",
	},
	{
		"id": "tough_as_nails",
		"name": "Tough as Nails",
		"cost_options": [4],
		"ability": "STR",
		"activation": "Active",
		"summary": "The hero's Strength resistance modifier improves by 1 step.",
		"source": "Player's Handbook p. 107; Table P26.",
	},
	{
		"id": "vigor",
		"name": "Vigor",
		"cost_options": [2, 3, 4],
		"ability": "CON",
		"activation": "Active",
		"summary": "Raises a durability rating: 2 points for +1 stun, 3 points for +1 wound, or 4 points for +1 mortal and +1 fatigue. Each listed benefit can be bought once.",
		"source": "Player's Handbook p. 107; Table P26.",
	},
	{
		"id": "willpower",
		"name": "Willpower",
		"cost_options": [4],
		"ability": "WIL",
		"activation": "Active",
		"summary": "The hero's Will resistance modifier improves by 1 step.",
		"source": "Player's Handbook p. 108; Table P26.",
	},
]

const FLAW_DEFINITIONS := [
	{
		"id": "alien_artifact_flaw",
		"name": "Alien Artifact",
		"bonus_options": [5],
		"ability": "Special",
		"summary": "A GM-designed alien item, experiment, or process is mostly a disadvantage, though it also has an unrelated positive side.",
		"source": "Player's Handbook p. 108-109; Table P27.",
	},
	{
		"id": "bad_luck",
		"name": "Bad Luck",
		"bonus_options": [6],
		"ability": "WIL",
		"summary": "The hero suffers a Critical Failure when the control die shows 19 or 20.",
		"source": "Player's Handbook p. 108; Table P27.",
	},
	{
		"id": "clueless",
		"name": "Clueless",
		"bonus_options": [2, 4, 6],
		"ability": "INT",
		"summary": "The GM secretly chooses a non-profession specialty skill the hero overestimates. The bonus option sets a +1, +2, or +3 step penalty to that skill.",
		"source": "Player's Handbook p. 108; Table P27.",
	},
	{
		"id": "clumsy",
		"name": "Clumsy",
		"bonus_options": [5],
		"ability": "DEX",
		"summary": "The hero has poor coordination and takes a +1 step penalty to Dexterity-based skill checks.",
		"source": "Player's Handbook p. 108; Table P27.",
	},
	{
		"id": "code_of_honor",
		"name": "Code of Honor",
		"bonus_options": [3],
		"ability": "WIL",
		"summary": "The hero follows a binding code agreed with the GM. Achievement awards can be reduced if the flaw is not roleplayed.",
		"source": "Player's Handbook p. 108-109; Table P27.",
	},
	{
		"id": "delicate",
		"name": "Delicate",
		"bonus_options": [3],
		"ability": "STR",
		"summary": "Successful Unarmed Attack checks inflict 1 stun on the hero. If current stun drops below half, the hero cannot use Unarmed Attack until recovering enough stun.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "dirt_poor",
		"name": "Dirt Poor",
		"bonus_options": [5],
		"ability": "PER",
		"summary": "The hero starts impoverished, has a creditor or obligation set by the GM, and takes a +1 step penalty to Personality-based checks when dealing upward socially or financially.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "forgetful",
		"name": "Forgetful",
		"bonus_options": [5],
		"ability": "INT",
		"summary": "The hero has trouble recalling details and takes a +1 step penalty to Intelligence-based skill checks.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "fragile",
		"name": "Fragile",
		"bonus_options": [3],
		"ability": "CON",
		"summary": "Damage hampers the hero, imposing a +1 step penalty to Stamina-endurance checks.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "infamy",
		"name": "Infamy",
		"bonus_options": [2, 4, 6],
		"ability": "PER",
		"summary": "The hero is known for a criminal or evil act. When triggered, the bonus option sets a +1, +2, or +3 step penalty to Personality-based skill checks.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "oblivious",
		"name": "Oblivious",
		"bonus_options": [4],
		"ability": "WIL",
		"summary": "The hero has trouble noticing details and takes a +1 step penalty to Awareness-perception checks.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "obsessed",
		"name": "Obsessed",
		"bonus_options": [2, 4, 6],
		"ability": "INT",
		"summary": "An agreed trigger distracts the hero. The bonus option sets a +1, +2, or +3 step penalty to actions not related to the obsession.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "old_injury",
		"name": "Old Injury",
		"bonus_options": [2, 4, 6],
		"ability": "STR",
		"summary": "An agreed physical trigger can flare once per scene. The bonus option sets wound damage of 1, 2 plus 1 stun, or 3 plus 1 stun; armor does not reduce it.",
		"source": "Player's Handbook p. 109; Table P27.",
	},
	{
		"id": "phobia",
		"name": "Phobia",
		"bonus_options": [2, 4, 6],
		"ability": "WIL",
		"summary": "An agreed broad fear hampers the hero. The bonus option sets a +1 or +2 step penalty to all actions, or freezing/fleeing for the highest option.",
		"source": "Player's Handbook p. 109-110; Table P27.",
	},
	{
		"id": "poor_looks",
		"name": "Poor Looks",
		"bonus_options": [3],
		"ability": "PER",
		"summary": "When appearance hurts an encounter, the hero takes a +1 step penalty to Personality-based skill checks, subject to GM and cultural context.",
		"source": "Player's Handbook p. 110; Table P27.",
	},
	{
		"id": "powerful_enemy",
		"name": "Powerful Enemy",
		"bonus_options": [2, 4, 6],
		"ability": "PER",
		"summary": "The hero has a far-reaching enemy. The bonus option determines how often and how broadly that enemy can affect the hero.",
		"source": "Player's Handbook p. 110; Table P27.",
	},
	{
		"id": "primitive",
		"name": "Primitive",
		"bonus_options": [2, 4, 6],
		"ability": "INT",
		"summary": "The hero struggles with modern technology. The bonus option sets a +1, +2, or +3 step penalty when using it, with possible awe or terror at the highest option.",
		"source": "Player's Handbook p. 110; Table P27.",
	},
	{
		"id": "slow",
		"name": "Slow",
		"bonus_options": [6],
		"ability": "DEX",
		"summary": "The hero has reduced reaction time and takes a +1 step penalty to action checks.",
		"source": "Player's Handbook p. 110; Table P27.",
	},
	{
		"id": "spineless",
		"name": "Spineless",
		"bonus_options": [2, 4, 6],
		"ability": "WIL",
		"summary": "The hero's Will resistance modifier is reduced by 1, 2, or 3 steps based on the selected bonus option.",
		"source": "Player's Handbook p. 110; Table P27.",
	},
	{
		"id": "temper",
		"name": "Temper",
		"bonus_options": [2, 4, 6],
		"ability": "WIL",
		"summary": "An agreed trigger sets off the hero. The bonus option imposes a +1, +2, or +3 step penalty to actions until the trigger ends and the hero calms down.",
		"source": "Player's Handbook p. 110; Table P27.",
	},
]

const PROFESSION_DEFINITIONS := [
	{
		"id": 0,
		"name": "Combat Spec",
		"code": "C",
		"secondary_code": "",
		"action_bonus": 3,
		"last_resort_bonus": 0,
		"ability_minimums": {
			"STR": 11,
			"CON": 9,
		},
		"notes": [
			"Action check score increased by 3.",
			"Choose one combat specialty for a -1 step situation bonus.",
			"Profession requirements: STR 11, CON 9. Source: Player's Handbook Table P1 p. 30.",
		],
	},
	{
		"id": 1,
		"name": "Diplomat (Combat Spec)",
		"code": "D",
		"secondary_code": "C",
		"action_bonus": 1,
		"last_resort_bonus": 0,
		"ability_minimums": {
			"WIL": 9,
			"PER": 11,
		},
		"notes": [
			"Action check score increased by 1.",
			"Starts with either Contacts or Resources.",
			"Secondary profession receives the skill cost bonus.",
			"Profession requirements: WIL 9, PER 11. Source: Player's Handbook Table P1 p. 30.",
		],
	},
	{
		"id": 2,
		"name": "Diplomat (Free Agent)",
		"code": "D",
		"secondary_code": "F",
		"action_bonus": 1,
		"last_resort_bonus": 0,
		"ability_minimums": {
			"WIL": 9,
			"PER": 11,
		},
		"notes": [
			"Action check score increased by 1.",
			"Starts with either Contacts or Resources.",
			"Secondary profession receives the skill cost bonus.",
			"Profession requirements: WIL 9, PER 11. Source: Player's Handbook Table P1 p. 30.",
		],
	},
	{
		"id": 3,
		"name": "Diplomat (Tech Op)",
		"code": "D",
		"secondary_code": "T",
		"action_bonus": 1,
		"last_resort_bonus": 0,
		"ability_minimums": {
			"WIL": 9,
			"PER": 11,
		},
		"notes": [
			"Action check score increased by 1.",
			"Starts with either Contacts or Resources.",
			"Secondary profession receives the skill cost bonus.",
			"Profession requirements: WIL 9, PER 11. Source: Player's Handbook Table P1 p. 30.",
		],
	},
	{
		"id": 4,
		"name": "Free Agent",
		"code": "F",
		"secondary_code": "",
		"action_bonus": 2,
		"last_resort_bonus": 1,
		"ability_minimums": {
			"DEX": 11,
			"WIL": 9,
		},
		"notes": [
			"Action check score increased by 2.",
			"Maximum last resorts increased by 1.",
			"Choose one resistance modifier for the Free Agent bonus.",
			"Profession requirements: DEX 11, WIL 9. Source: Player's Handbook Table P1 p. 30.",
		],
	},
	{
		"id": 5,
		"name": "Tech Op",
		"code": "T",
		"secondary_code": "",
		"action_bonus": 1,
		"last_resort_bonus": 0,
		"ability_minimums": {
			"DEX": 9,
			"INT": 11,
		},
		"notes": [
			"Action check score increased by 1.",
			"Uses Accelerated Learning when advancing.",
			"Profession requirements: DEX 9, INT 11. Source: Player's Handbook Table P1 p. 30.",
		],
	},
	{
		"id": 6,
		"name": "Mindwalker",
		"code": "",
		"secondary_code": "",
		"action_bonus": 1,
		"last_resort_bonus": 0,
		"ability_minimums": {
			"CON": 9,
			"INT": 9,
			"WIL": 11,
		},
		"notes": [
			"Action check score increased by 1.",
			"Choose one psionic broad skill and its specialties for a -1 step bonus.",
			"Profession requirements: CON 9, INT 9, WIL 11. Source: Player's Handbook Table P1 p. 30.",
		],
	},
]

